const types = {
    GET_POSTS: 'GET_POSTS',
    CREATE_POST: 'CREATE_POST',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',
    GET_TEMPLATES: 'GET_TEMPLATES',
    GET_TEMPLATES_AS_POSTS: 'GET_TEMPLATES_AS_POSTS',
    CREATE_TEMPLATE: 'CREATE_TEMPLATE',
    UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',
    DELETE_TEMPLATE: 'DELETE_TEMPLATE'
};

export default types;